# Generated by Django 5.2.8 on 2025-12-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(null=True)),
                ('infos_dynamique', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
