# Generated by Django 5.2.8 on 2025-12-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='workflow_status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('assigned', 'Assigné'), ('contacted', 'Contacté'), ('qualified', 'Qualifié'), ('converted', 'Converti'), ('rejected', 'Rejeté'), ('closed', 'Fermé')], default='new', max_length=50),
        ),
    ]
